run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - gofumpt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - misspell
    - gocritic
    - revive
    - gocyclo
    - dupl
    - goimports

linters-settings:
  gofumpt:
    extra-rules: true

  govet:
    check-shadowing: true

  staticcheck:
    checks: ["all"]

  revive:
    rules:
      - name: exported
        disabled: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gocyclo