site_name: Accumulate DID
site_description: Decentralized Identifiers on Accumulate Protocol
site_url: https://accumulate-did.docs
repo_url: https://github.com/opendlt/accu-did
repo_name: opendlt/accu-did

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - API Reference:
    - Resolver: resolver.md
    - Registrar: registrar.md
    - Universal Drivers: universal.md
  - Interoperability:
    - DIDComm v2: interop/didcomm.md
    - SD-JWT: interop/sd-jwt.md
    - BBS+ Signatures: interop/bbs.md
  - Developer Guide:
    - Go Quickstart: quickstart-go.md

plugins:
  - search
  - autorefs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opendlt/accu-did